name: flask_app_env
channels:
  - defaults
dependencies:
  - ca-certificates=2023.05.30
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=1.1.1u
  - pip=23.1.2
  - python=3.9.13
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - blinker==1.6.2
      - click==8.1.3
      - flask==2.3.2
      - importlib-metadata==6.7.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - markupsafe==2.1.3
      - werkzeug==2.3.6
      - zipp==3.15.0
